//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procrastinator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int CourseCode { get; set; }
        public int SubjectTypeId { get; set; }
        public int CreditHours { get; set; }
        public int DifficultyRating { get; set; }
    
        public virtual SubjectType SubjectType { get; set; }
    }
}
